### ISSUE TITLE
Found your stackoverflow but have rep < 50 so can't comment

### ISSUE THREAD

**Issue by GhitaCristian** [upupming/HITMers-firebase-server#1]
I tried to mimic firebase hosting the way you've done it to make it work with koa. The only difference is that my koa server js file is outside `functions` folder but I am not sure that that is the problem. 

I can use `firebase server --only function, hosting` and it works great, exactly as expected but when I do `firebase deploy` it throws `Error: Cannot find module '../index'` - index being my server file. 

I can do `firebase deploy --only hosting` but can't do it with functions. Can you please help me?

**Comment by upupming** [comment]
Hi @GhitaCristian , sorry for the late reply (because I was not watching this repo).

The reason why things are working well when you run `firebase serve` is that it will [run locally](https://firebase.google.com/docs/functions/local-emulator#serve_http_functions_from_the_command_line):
>This command emulates hosting and functions on locally hosted URLs.

You can simply move `index.js` into under folder `functions`.  Only files under `functions` will actually be uploaded to firebase cloud.
